# Generated by Django 6.0.1 on 2026-01-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parententitysimple',
            name='child_entities',
        ),
        migrations.RemoveField(
            model_name='dependententitysimple',
            name='parent_entity',
        ),
        migrations.RemoveField(
            model_name='extendedentitysimple',
            name='parent_entity',
        ),
        migrations.AlterField(
            model_name='childentity',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='childentity',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='dependententity',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='dependententity',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='extendedentity',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='extendedentity',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='parententity',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='parententity',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time'),
        ),
        migrations.DeleteModel(
            name='ChildEntitySimple',
        ),
        migrations.DeleteModel(
            name='DependentEntitySimple',
        ),
        migrations.DeleteModel(
            name='ExtendedEntitySimple',
        ),
        migrations.DeleteModel(
            name='ParentEntitySimple',
        ),
    ]
